from __future__ import annotations

from collections.abc import Callable, Iterable, Sequence
from pathlib import Path
from typing import ContextManager, Protocol, Self

from .domain import DrawingFileReference, QuoteDraft, QuoteDrawingLink, QuoteFilters, QuoteRecord, QuoteStats


class QuoteRepository(Protocol):
    def add(self, draft: QuoteDraft) -> QuoteRecord: ...

    def get(self, quote_id: int) -> QuoteRecord | None: ...

    def list(self, filters: QuoteFilters, *, limit: int, offset: int) -> list[QuoteRecord]: ...

    def count(self, filters: QuoteFilters) -> int: ...

    def latest(self, *, customer_name: str, bld_no: str) -> QuoteRecord | None: ...

    def update(self, quote_id: int, draft: QuoteDraft, *, expected_version: int) -> QuoteRecord | None: ...

    def delete(self, quote_id: int) -> QuoteRecord | None: ...

    def add_revision(self, before: QuoteRecord, after: QuoteRecord, *, actor: str) -> None: ...

    def stats(self) -> QuoteStats: ...

    def audit(self, action: str, quote: QuoteRecord, *, actor: str) -> None: ...

    def list_by_quote_no(self, quote_no: str) -> list[QuoteRecord]: ...

    def customer_summary(self, customer_id: int, customer_name: str) -> dict[str, object]: ...

    def customer_history(self, customer_id: int, customer_name: str, *, limit: int) -> list[dict[str, object]]: ...

    def customer_product_options(self, customer_id: int, customer_name: str) -> list[dict[str, str]]: ...

    def rename_customer_references(self, customer_id: int, old_name: str, new_name: str) -> int: ...

    def link_drawing(self, quote_record_id: int, drawing_file_id: int, *, actor: str) -> None: ...

    def unlink_drawing(self, quote_record_id: int, link_id: int) -> bool: ...

    def drawing_links(self, quote_record_ids: Sequence[int]) -> dict[int, list[QuoteDrawingLink]]: ...


class QuoteUnitOfWork(Protocol):
    repository: QuoteRepository

    def __enter__(self) -> Self: ...

    def __exit__(self, exc_type, exc, traceback) -> None: ...

    def commit(self) -> None: ...


QuoteUnitOfWorkFactory = Callable[[], QuoteUnitOfWork]


class QuoteImportPort(Protocol):
    def parse(self, path: Path, *, customer_name: str, currency: str) -> dict: ...

    def encode(self, rows: list[dict]) -> str: ...

    def decode(self, payload: str) -> list[dict]: ...


class ImportLockBusyError(RuntimeError):
    pass


class ImportLockPort(Protocol):
    def __call__(self, owner: str, purpose: str) -> ContextManager[None]: ...


class ProductCatalogPort(Protocol):
    def exists(self, bld_no: str) -> bool: ...


class CustomerDirectoryPort(Protocol):
    def exists(self, customer_name: str) -> bool: ...

    def find_id(self, customer_name: str) -> int | None: ...

    def find_active_id(self, customer_id: int | None, customer_name: str) -> int | None: ...


class ContractDocumentDirectoryPort(Protocol):
    def list_by_quote_no(self, quote_no: str) -> list[dict[str, object]]: ...


class CustomerDrawingDirectoryPort(Protocol):
    def file_references(self, file_ids: Iterable[int]) -> dict[int, DrawingFileReference]: ...

    def linkable_versions(self, customer_id: int) -> list[dict[str, object]]: ...


QuoteRows = Iterable[dict[str, object]]
